### ISSUE TITLE
Not working even if i install opencv on phone

### ISSUE THREAD

**Issue by junlong602** [eaglesky/HandGestureApp#2]
It says opencv was not initialized correctly. App will close. Do you know how to solve this?

**Comment by eaglesky** [comment]
Hi Jun Long,

Are you building the app using Android Studio? If so, did you build the OpenCV samples successfully?

Thanks.

**Comment by junlong602** [comment]
Yup. I'm building using Android Studio. Let me try building the samples over there because I only installed the samples using the apk given with the opencv download file.

**Comment by junlong602** [comment]
Every sample that I tried to build using my android studio seems to have the same error. I cant solve it for days... Don't know what's wrong

**Comment by eaglesky** [comment]
So this issue is actually not related to this project. Close it for now. @junlong602  we can talk by email about it.
